events {
	worker_connections 1024;
}

http {
	# Hardening: hide nginx ver tokens to prevent banner grabbing
	server_tokens off;

	upstream backend_api {
		# 'api' matches the service name we will define in Docker compose
		server api:8000;
	}

	server {
		# Change :80 to :8080 because Wolfi's non-root env
		listen 8080;
		server_name localhost;

		# Standard headers to forward the client's real connection detail
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;

		# Core routing rule: Pass everything to the FastAPI app
		location / {
			proxy_pass http://api:8000;
		}

		# Specific optimization for SRE health monitoring
		location /health {
			proxy_pass http://backend_api/health;

			# Hardening: Turn off access logging for health checks
			# (we are overdoing it a little)
			access_log off;
		}
	}
}
